version: "3"

services:
  php:
    container_name: php
    image: php:7.2-apache
    ports:
      - 8089:80
    volumes:
      - ./laravel_app:/opt/lamp/htdocs
    depends_on:
      - db
  db:
    container_name: database
    image: mysql:5.7
    ports:
      - 3306:3306
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=secret.
      - MYSQL_DATABASE=yourdb
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=.mypwd
